kumuluzee:
  name: l-assistente-del-ristorante
  version: 1.0.0
  openapi-mp:
    ui:
      server-auto-config:
        enabled: true

  env:
    name: dev
  datasources:
    - jndi-name: jdbc/LAssistenteDelRistoranteDS
      connection-url: jdbc:postgresql://db-container:5432/prpodb
      username: username
      password: password123
      max-pool-size: 20

  dev:
    scan-libraries:
      - entities
      - services

  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/LAssistenteDelRistoranteDS
      http-health-check:
        type: liveness
        connection-url: https://api.calorieninjas.com/v1/nutrition
      headers:
        X-Api-Key: "7WOjamiscs0YLNXltficlg==1Axu7GutiFny1nJe"

