version: '3.8'

services:
  database:
    image: postgres
    container_name: db-container
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: prpodb
    ports:
      - "8023:5432"
#    networks:
#      - app-network

  backend:
    build:
      context: ./LAssistenteDelRistorante
    image: backend-image
    container_name: backend-container
    environment:
      DB_HOST: db-container
      DB_PORT: 5432
      DB_USER: username
      DB_PASSWORD: password123
    ports:
      - "8080:8080"
    depends_on:
      - database
#    networks:
#      - app-network

  frontend:
    build:
      context: ./frontend
    image: frontend-image
    container_name: frontend-container
    ports:
      - "8088:80"
#    networks:
#      - app-network

#networks:
#  app-network:
#    driver: bridge
